---
- name: db.ini
  template: src=db.ini.j2 dest={{ omekadir }}/db.ini
  sudo: true
- name: chmod db.ini
  file: path={{ omekadir }}/db.ini mode=0666
- name: cp config.ini
  template: src=config.ini dest={{ omekadir }}/application/config/config.ini
# - name: config.ini debug
#   ini_file: dest={{ omekadir }}/application/config/config.ini
#             section=site
#             option=debug.exceptions
#             value={{ debug }}
# - name: cp tests/config.ini
#   command: cp {{ omekadir }}/application/tests/config.ini {{ omekadir }}/application/tests/config.ini
# - name: tests/config.ini db.username
#   ini_file: dest={{ omekadir }}/application/tests/config.ini
#             section=testing
#             option=db.username
#             value=omeka
# - name: tests/config.ini db.password
#   ini_file: dest={{ omekadir }}/application/tests/config.ini
#             section=testing
#             option=db.password
#             value=omeka
# - name: tests/config.ini db.dbname
#   ini_file: dest={{ omekadir }}/application/tests/config.ini
#             section=testing
#             option=db.dbname
#             value=omeka
# - name: .htaccess
#   template: src=.htaccess dest={{ omekadir }}/.htaccess
- name: APPLICATION_ENV
  lineinfile: dest={{ omekadir }}/.htaccess
              backrefs=yes
              regexp='# (SetEnv APPLICATION_ENV .*)'
              line='\1'
- name: files
  file: path={{ omekadir }}/files recurse=yes mode=0777
- name: hostname
  lineinfile: line='127.0.0.1        {{ hostname }}' state=present insertafter=EOF dest=/etc/hosts
  sudo: true
  when: hostname is defined
