---
# The play operates on the local (Ansible control) machine.
- name: Stage instance(s)
  hosts: local
  connection: local
  sudo: True
  gather_facts: false

  tasks:
    - debug: 'msg="System {{ inventory_hostname }}"'
    - include: setup.yml
    - include: NLTK.yml
    - include: mallet.yml
      vars:
        malletdir: /dhbox/mallet
    - include: rstudio.yml
    - include: omeka.yml
      vars:
        omekadir: /var/www/omeka
    - name: create root user
      user: name=dhbox
          state=present
          groups="sudo"
          password={{ password }}
          comment="DH Box sudo account"
  handlers:
   - name: restart apache2
     sudo: True
     service: name=apache2 state=restarted