VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

# for i in 8081..10000
config.vm.network :forwarded_port, guest: 8787, host: 8787
# end

  config.vm.provision "shell",
    inline: "apt-get -y update && apt-get -y install docker.io && ln -sf /usr/bin/docker.io /usr/local/bin/docker"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 1]
  end

end
